trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: 'Certificate'
- name: 'solution'
  value: '**/*.sln'
- name: 'buildPlatform'
  value: 'x64'
- name: 'buildConfiguration'
  value: 'Release'
- name: 'msixInstallUrl'
  value: http://10.244.0.24
- name: 'packageVersion'
  value: 1.0.0
- name: 'packageName'
  value: 'Terminal'

jobs: 
- job: BuildMSIX
  strategy: 
    matrix: 
      Preview:
        channelName: 'preview'
        packageIdSuffix: '-preview'
        packageNameSuffix: ' [PREVIEW]'
      Production:
        channelName: 'production'
        packageIdSuffix: ''
        packageNameSuffix: ''
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [xml]$manifest= get-content "Terminal\Package.appxmanifest"
        $manifest.Package.Identity.Version = "$(packageVersion).$(Build.BuildId)"
        $manifest.Package.Identity.Name = "demo-864d9095-955f-4d3c-adb0-6574a5acb88b$(packageIdSuffix)"
        $manifest.Package.Properties.DisplayName = "$(packageName)$(packageNameSuffix)"
        $manifest.Package.Applications.Application.VisualElements.DisplayName = "$(packageName)$(packageNameSuffix)"
        $manifest.save("Terminal\Package.appxmanifest")

  - task: DownloadSecureFile@1
    name: mySecureFile
    displayName: 'Download CA certificate'
    inputs:
      secureFile: 'Terminal_TemporaryKey.pfx'
  
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Start adding the PFX file to the certificate store."
        $pfxpath = '$(mySecureFile.secureFilePath)'
        $password = '$(password)'
        Add-Type -AssemblyName System.Security
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
        $cert.Import($pfxpath, $password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
        $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
        $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
        $store.Add($cert)
        $store.Close()
    displayName: 'Install PFX File'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/restore /p:AppInstallerUri=$(msixInstallUrl)/$(channelName) /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)/$(channelName)" /p:UapAppxPackageBuildMode=StoreAndSideload /p:GenerateAppInstallerFile=true /p:PackageCertificateKeyFile="$(mySecureFile.secureFilePath)" /p:PackageCertificatePassword="$(mySecureFile.secret)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  #- task: Docker@2
  #  inputs:
  #    command: 'build'
  #    Dockerfile: '**/Dockerfile'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'